[theme]
primaryColor = "#42A5F5"
backgroundColor = "#0a0e17"
secondaryBackgroundColor = "#121828"
textColor = "#ECEFF1"
font = "sans serif"

[server]
maxUploadSize = 10
runOnSave = false
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false
